Update main.py and model.py to account for removal of VerificationMaterials from Sigstore
sigstore/model-transparency pull request #212
Opened 2024-06-17 19:02 UTC by Andrew-Gan

#### Summary

Sigstore 3.0 has removed VerificationMaterials as stated in [Release v3.0.0](https://github.com/sigstore/sigstore-python/releases/tag/v3.0.0)
Instead, verifier takes in bundles as argument now.

#### Release Note

Bug fix
Unable to run main.py according to README.md instructions using dependencies in install/requirements_Linux.txt.

#### Documentation

2024-06-17 19:37 UTC, mihaimaruseac reviewed
Please remove unrelated changes to main.py, none of those are needed.

Also, instead of commenting stale code, please remove it

2024-06-17 23:48 UTC, mihaimaruseac approved these changes
This LGTM, but leaving to @laurentsimon / @haydentherapper for final approval

2024-06-17 23:49 UTC, mihaimaruseac commented
Actually, can you make your commits be signed, please? We use DCO, see https://github.com/sigstore/model-transparency/blob/main/CONTRIBUTING.md

2024-06-19 16:10 UTC, mihaimaruseac approved these changes

2024-06-19 16:12 UTC, mihaimaruseac requested changes

2024-06-19 16:12 UTC, mihaimaruseac commented on model_signing/model.py
>              contentio = io.BytesIO(Serializer.serialize_v1(
The `contentio` variable becomes unused now. Which means that we still don't serialize the model when we verify.

2024-06-20 15:04 UTC, laurentsimon commented
@spencerschrock I think we missed the regression when updating our deps because we don't have e2e tests https://github.com/sigstore/model-transparency/issues/5. This issue is another good starting one

2024-06-21 01:47 UTC, mihaimaruseac submitted a review, later dismissed

2024-06-21 19:59 UTC, mihaimaruseac commented
Can you amend the last commit please to pass the DCO check? (same as https://github.com/sigstore/model-transparency/pull/212#issuecomment-2174639942)

2024-06-24 15:03 UTC, mihaimaruseac approved these changes
Thank you!

2024-06-25 16:30 UTC, merged